# Generated by Django 6.0.7 on 2026-07-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
