# Generated by Django 6.0.7 on 2026-07-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, db_column='correo', max_length=255, null=True, unique=True),
        ),
    ]
