# Generated by Django 6.0.7 on 2026-07-18 05:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_categorias',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), name='uq_categoria_nombre_norm')],
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_localizaciones',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), name='uq_localizacion_nombre_norm')],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_activo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('costo_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('vida_util_anios', models.IntegerField()),
                ('estado_depreciacion', models.CharField(choices=[('DEPRECIANDO', 'Depreciando'), ('TOTALMENTE_DEPRECIADO', 'Totalmente depreciado')], max_length=30)),
                ('valor_libros_actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('depreciacion_acumulada_actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('factura', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='assets.categoria')),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='assets.localizacion')),
            ],
            options={
                'db_table': 'activo',
                'constraints': [models.CheckConstraint(condition=models.Q(('costo_original__gt', 0)), name='ck_activo_costo_original_positivo'), models.CheckConstraint(condition=models.Q(('fecha_inicio__gte', models.F('fecha_adquisicion'))), name='ck_activo_fecha_inicio_valida'), models.CheckConstraint(condition=models.Q(('vida_util_anios__gt', 0)), name='ck_activo_vida_util_positiva'), models.CheckConstraint(condition=models.Q(('estado_depreciacion__in', ['DEPRECIANDO', 'TOTALMENTE_DEPRECIADO'])), name='ck_activo_estado_depreciacion'), models.CheckConstraint(condition=models.Q(('valor_libros_actual__gte', 0)), name='ck_activo_valor_libros_no_negativo'), models.CheckConstraint(condition=models.Q(('depreciacion_acumulada_actual__gte', 0)), name='ck_activo_depreciacion_acumulada_no_negativa'), models.CheckConstraint(condition=models.Q(('depreciacion_acumulada_actual__lte', models.F('costo_original'))), name='ck_activo_depreciacion_no_supera_costo')],
            },
        ),
    ]
