# Generated by Django 6.0.7 on 2026-07-21 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('ALTA', 'Alta / Registro inicial'), ('CAMBIO_COSTO', 'Cambio de costo'), ('CAMBIO_VIDA_UTIL', 'Cambio de vida útil'), ('CAMBIO_AREA_TIPO', 'Cambio de área / categoría'), ('BAJA', 'Baja / Retiro'), ('REVERSION_BAJA', 'Reversión de baja')], max_length=30)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('fecha_efectiva', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='assets.activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimiento',
                'ordering': ['-fecha_efectiva', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo_evento__in', ['ALTA', 'CAMBIO_COSTO', 'CAMBIO_VIDA_UTIL', 'CAMBIO_AREA_TIPO', 'BAJA', 'REVERSION_BAJA'])), name='ck_movimiento_tipo_evento')],
            },
        ),
    ]
