# Generated by Django 6.0.7 on 2026-07-21 04:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_proveedor_activo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_marcas',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), name='uq_marca_nombre_norm')],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='assets.marca'),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activa', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='assets.marca')),
            ],
            options={
                'db_table': 'catalogo_modelos',
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='assets.modelo'),
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalogo_origenes',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), name='uq_origen_nombre_norm')],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='assets.origen'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(models.F('marca'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('nombre')), name='uq_modelo_marca_nombre_norm'),
        ),
    ]
