# Generated by Django 6.0.7 on 2026-07-22 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_categoria_prefijo_marca_activo_marca_modelo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimiento',
            name='ck_movimiento_tipo_evento',
        ),
        migrations.AddField(
            model_name='activo',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_evento',
            field=models.CharField(choices=[('ALTA', 'Alta / Registro inicial'), ('CAMBIO_COSTO', 'Cambio de costo'), ('CAMBIO_VIDA_UTIL', 'Cambio de vida útil'), ('CAMBIO_AREA_TIPO', 'Cambio de área / categoría'), ('CAMBIO_FECHAS', 'Cambio de fechas'), ('BAJA', 'Baja / Retiro'), ('REVERSION_BAJA', 'Reversión de baja')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_evento__in', ['ALTA', 'CAMBIO_COSTO', 'CAMBIO_VIDA_UTIL', 'CAMBIO_AREA_TIPO', 'CAMBIO_FECHAS', 'BAJA', 'REVERSION_BAJA'])), name='ck_movimiento_tipo_evento'),
        ),
    ]
