# Generated by Django 6.0.7 on 2026-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_editar_activo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activo',
            name='ck_activo_vida_util_positiva',
        ),
        migrations.AddConstraint(
            model_name='activo',
            constraint=models.CheckConstraint(condition=models.Q(('vida_util_anios__gte', 0)), name='ck_activo_vida_util_no_negativa'),
        ),
    ]
