# Generated by Django 6.0.7 on 2026-07-23 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_vida_util_permite_cero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('VENTA', 'Venta'), ('DESECHO', 'Desecho u obsolescencia'), ('ROBO_PERDIDA', 'Robo o pérdida')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_efectiva', models.DateField()),
                ('archivo_respaldo', models.FileField(upload_to='respaldos_retiro/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVERTIDA', 'Revertida'), ('DEFINITIVA', 'Definitiva')], default='PENDIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros', to='assets.activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retiro',
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='assets.retiro'),
        ),
        migrations.AddConstraint(
            model_name='retiro',
            constraint=models.CheckConstraint(condition=models.Q(('motivo__in', ['VENTA', 'DESECHO', 'ROBO_PERDIDA'])), name='ck_retiro_motivo'),
        ),
        migrations.AddConstraint(
            model_name='retiro',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'REVERTIDA', 'DEFINITIVA'])), name='ck_retiro_estado'),
        ),
        migrations.AddConstraint(
            model_name='retiro',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'REVERTIDA'), _negated=True), fields=('activo',), name='uq_retiro_activo_no_revertido'),
        ),
    ]
