# Generated by Django 6.0.7 on 2026-07-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_retiro_trigger_inmutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
