# Generated by Django 6.0.7 on 2026-07-31 02:40

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_activo_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='archivo_respaldo',
            field=models.FileField(storage=assets.models.obtener_almacenamiento_respaldos, upload_to=assets.models.ruta_respaldo_retiro),
        ),
    ]
