"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

from config.env import resolver_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# SECURITY WARNING: en produccion DJANGO_SECRET_KEY es obligatorio (fail-closed).
SECRET_KEY = resolver_secret_key(os.environ, DEBUG)

# DA16: cada empresa se sirve desde su propio subdominio (ej. acme.localhost
# en desarrollo). Se acepta el dominio base y cualquier subdominio suyo.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,.localhost').split(',')
    if h.strip()
]


# Application definition

SHARED_APPS = [
    'django_tenants',            # obligatorio primero
    'corsheaders',
    'companies',                 # registro de empresas (schema publico)
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'rest_framework',
]

TENANT_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'rest_framework_simplejwt.token_blacklist',  # per-tenant: FK a accounts.Usuario
    'accounts',                  # usuarios + auth (schema de cada empresa)
    'assets',                    # activos y catalogos (schema de cada empresa)
]

INSTALLED_APPS = list(SHARED_APPS) + [a for a in TENANT_APPS if a not in SHARED_APPS]

TENANT_MODEL = 'companies.Empresa'
TENANT_DOMAIN_MODEL = 'companies.Domain'
AUTH_USER_MODEL = 'accounts.Usuario'

DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',   # fija el schema por Host, primero
    'corsheaders.middleware.CorsMiddleware',                 # antes de CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DA01 exige multitenencia por schema mediante django-tenants: el motor
# django_tenants.postgresql_backend enruta cada conexion al schema correcto
# segun TENANT_MODEL/TENANT_DOMAIN_MODEL (app `companies`).

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.environ.get('DB_NAME', 'activos_fijos'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5430'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# --- API / autenticacion ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Cookies donde vive el JWT (nunca en el body ni en localStorage).
AUTH_COOKIE_ACCESS = 'access'
AUTH_COOKIE_REFRESH = 'refresh'
AUTH_COOKIE_SAMESITE = 'Lax'
AUTH_COOKIE_SECURE = not DEBUG          # en dev (DEBUG=True) permite http://demo.localhost
AUTH_COOKIE_REFRESH_PATH = '/api/auth'  # el refresh solo se envia a los endpoints de auth

# CSRF: el token DEBE ser legible por JS para reenviarlo en X-CSRFToken.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
# En produccion, usar un comodin para todos los subdominios de empresas
# (ej. https://*.sistema.com) — Django soporta el prefijo '*.' desde la
# version 4.0. Una lista de origenes literales no escala a las empresas
# nuevas que se dan de alta bajo el dominio wildcard (DA16).
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://demo.localhost:5173',
    ).split(',')
    if o.strip()
]

# CORS: en la Opcion B el frontend vive en un subdominio distinto al backend
# (mismo dominio padre). Se permite por regex de subdominios y con credenciales
# para que la cookie httpOnly viaje. Vacio en dev (el proxy de Vite hace mismo
# origen, sin CORS). En prod, ej: ^https://[a-z0-9-]+\.sistema\.com$
CORS_ALLOWED_ORIGIN_REGEXES = [
    r.strip()
    for r in os.environ.get('DJANGO_CORS_ALLOWED_ORIGIN_REGEXES', '').split(',')
    if r.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Cache local para el throttle del login (DA08). En produccion se cambia el backend (DA07).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
