# Generated by Django 6.0.7 on 2026-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='subdominio',
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
